project:
  type: book
  title: "Psicologia dell'Intelligenza Umana"
  output-dir: website 

format:
  html:
    number-sections: true
    toc: false
    css: custom.css
    page-layout: full
    include-in-header:
       text: |
         <link rel="shortcut icon" href="favicon.ico"/>
         <script data-goatcounter="https://intelligenza.goatcounter.com/count"
               async src="//gc.zgo.at/count.js"></script>

book:
  title: "Psicologia dell'Intelligenza Umana"
  author:
    - name: '<a href="https://enricotoffalini.github.io" target="_blank">Enrico Toffalini</a>'
      affiliation: "Dipartimento di Psicologia Generale, Universit√† di Padova" 
  chapters:
    - file: index.qmd
      text: "Introduzione"
    - file: references.qmd
      text: "Riferimenti bibliografici"

    - part: "<b>Professione</b>"
      chapters:
        - professione-pagine/elenco-test-italia.qmd    
    - part: "<b>Divulgazione</b>"
      chapters:
        - divulgazione-pagine/domande-risposte.qmd
        - divulgazione-pagine/flynn-effetto-flynn.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: false

    