project:
  type: book
  title: "Psicologia dell'Intelligenza Umana"
  output-dir: website 

format:
  html:
    number-sections: true
    toc: false
    css: custom.css
    page-layout: full
    include-in-header:
       text: |
         <link rel="shortcut icon" href="figure/favicon.png"/>

book:
  title: "Psicologia dell'Intelligenza Umana"
  author:
    - name: "Enrico Toffalini"
      affiliation: "Dipartimento di Psicologia Generale, Universit√† di Padova" 
  chapters:
    - file: index.qmd
      text: "Introduzione"
    - file: references.qmd
      text: "Riferimenti bibliografici"
    
    - part: "<b>Divulgazione</b>"
      chapters:
        - divulgazione/domande-risposte.qmd
        - divulgazione/flynn-effetto-flynn.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: false

    